services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/vhost.conf:ro
      - ./dev/tls/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./dev/tls/key.pem:/etc/nginx/ssl/key.pem:ro
    extra_hosts:
      - 'node1.oap.devnet:host-gateway'
      - 'node2.oap.devnet:host-gateway'
      - 'node3.oap.devnet:host-gateway'
      - 'node4.oap.devnet:host-gateway'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://node1.oap.devnet/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - 80:80
      - 443:443
    profiles:
      - openaudio-dev
      - integration-tests

  eth-ganache:
    image: audius/eth-ganache:latest
    restart: unless-stopped
    command: bash /tmp/scripts/eth-ganache.sh
    stop_grace_period: 0s
    pull_policy: always
    volumes:
      - ./dev/scripts/eth-ganache.sh:/tmp/scripts/eth-ganache.sh
    deploy:
      mode: global
    ports:
      - 8545:8545
    profiles:
      - openaudio-dev
      - integration-tests

  openaudio-1:
    image: ${OPENAUDIO_IMAGE:-audius/openaudio:dev}
    restart: unless-stopped
    env_file:
      - ./dev/env/openaudio-1.env
    extra_hosts:
      - 'node1.oap.devnet:host-gateway'
      - 'node2.oap.devnet:host-gateway'
      - 'node3.oap.devnet:host-gateway'
      - 'node4.oap.devnet:host-gateway'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://node1.oap.devnet/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    profiles:
      - openaudio-dev
      - integration-tests

  openaudio-2:
    image: ${OPENAUDIO_IMAGE:-audius/openaudio:dev}
    restart: unless-stopped
    env_file:
      - ./dev/env/openaudio-2.env
    extra_hosts:
      - 'node1.oap.devnet:host-gateway'
      - 'node2.oap.devnet:host-gateway'
      - 'node3.oap.devnet:host-gateway'
      - 'node4.oap.devnet:host-gateway'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://node2.oap.devnet/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    profiles:
      - openaudio-dev
      - integration-tests

  openaudio-3:
    image: ${OPENAUDIO_IMAGE:-audius/openaudio:dev}
    restart: unless-stopped
    env_file:
      - ./dev/env/openaudio-3.env
    extra_hosts:
      - 'node1.oap.devnet:host-gateway'
      - 'node2.oap.devnet:host-gateway'
      - 'node3.oap.devnet:host-gateway'
      - 'node4.oap.devnet:host-gateway'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://node3.oap.devnet/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    profiles:
      - openaudio-dev
      - integration-tests

  openaudio-4:
    image: ${OPENAUDIO_IMAGE:-audius/openaudio:dev}
    restart: unless-stopped
    env_file:
      - ./dev/env/openaudio-4.env
    extra_hosts:
      - 'node1.oap.devnet:host-gateway'
      - 'node2.oap.devnet:host-gateway'
      - 'node3.oap.devnet:host-gateway'
      - 'node4.oap.devnet:host-gateway'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://node4.oap.devnet/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    profiles:
      - openaudio-dev
      - integration-tests

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./dev/adminer/plugins-enabled/login-servers.php:/var/www/html/plugins-enabled/login-servers.php
    extra_hosts:
      - 'node1.oap.devnet:host-gateway'
      - 'node2.oap.devnet:host-gateway'
      - 'node3.oap.devnet:host-gateway'
      - 'node4.oap.devnet:host-gateway'
    profiles:
      - openaudio-dev

  test-integration:
    image: ${OPENAUDIO_TEST_HARNESS_IMAGE:-audius/openaudio:harness}
    command: go test -v -count=1 -timeout=90s ./pkg/integration_tests/...
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    env_file:
      - ./dev/env/test-core.env
    extra_hosts:
      - 'node1.oap.devnet:host-gateway'
      - 'node2.oap.devnet:host-gateway'
      - 'node3.oap.devnet:host-gateway'
      - 'node4.oap.devnet:host-gateway'
    depends_on:
      openaudio-1:
        condition: service_started
      openaudio-2:
        condition: service_started
      openaudio-3:
        condition: service_started
      openaudio-4:
        condition: service_started
      eth-ganache:
        condition: service_healthy
      nginx:
        condition: service_healthy
    profiles:
      - integration-tests

  test-mediorum-unittests:
    image: ${OPENAUDIO_TEST_HARNESS_IMAGE:-audius/openaudio:harness}
    command: go test -v -count=1 -timeout=60s ./pkg/mediorum/...
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    environment:
      NETWORK: test
      dbUrlTemplate: 'postgres://postgres:postgres@localhost:5432/m%d'
      dbUrl: 'postgres://postgres:postgres@localhost:5432/mediorum_test'
    profiles:
      - mediorum-unittests

  test-unittests:
    image: ${OPENAUDIO_TEST_HARNESS_IMAGE:-audius/openaudio:harness}
    command:
      - go
      - test
      - -v
      - -count=1
      - -timeout=60s
      - ./pkg/core/...
      - ./pkg/lifecycle/...
      - ./pkg/rewards/...
      - ./pkg/common/...
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    profiles:
      - unittests
